#!/usr/bin/env python3
"""
Promote reviewed Reddit candidates into a publishable spots file.

Review model (deliberately simple + safe):
  1. reddit_ingest.py writes candidates.jsonl (one candidate per line).
  2. YOU review: open candidates.jsonl and delete any junk lines, OR rely on
     the --min-conf / --min-upvotes gates below. Auto-collected spots always
     carry needs_review + legal_status:"unverified" so nothing pretends to be
     hand-vetted.
  3. promote.py assigns ids, dedupes, and writes ingested-spots.js
     (window.INGESTED_SPOTS) — the app loads it just like the other spot files.

Usage:
    python promote.py                       # promote all candidates that pass gates
    python promote.py --min-conf 0.9        # only exactly-located spots
    python promote.py --min-upvotes 50      # only well-loved posts

The output is a static JS file; wiring it into the live app (adding one
<script> tag + a spread in data.js) is a one-line follow-up we do together,
so a bad batch can never silently hit production.
"""
import json, re, argparse, pathlib
import config as C

HERE = pathlib.Path(__file__).resolve().parent
ID_START = 1000  # ingested spots live in their own id range, above hand-curated ones


def norm(s):
    return re.sub(r"[^a-z0-9]", "", s.lower())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-conf", type=float, default=0.5)
    ap.add_argument("--min-upvotes", type=int, default=C.MIN_UPVOTES)
    ap.add_argument("--out", default="ingested-spots.js")
    args = ap.parse_args()

    cand_path = HERE / C.CANDIDATES_FILE
    if not cand_path.exists():
        raise SystemExit(f"No {cand_path} yet — run reddit_ingest.py first.")

    seen_keys, spots = set(), []
    total = passed = 0
    for line in cand_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        total += 1
        c = json.loads(line)
        if c.get("location_confidence", 0) < args.min_conf:
            continue
        if c.get("upvotes", 0) < args.min_upvotes:
            continue
        key = (norm(c["name"])[:24], round(c["lat"], 2), round(c["lng"], 2))
        if key in seen_keys:
            # same spot from another post -> attach its embed instead of duplicating
            for s in spots:
                if (norm(s["name"])[:24], round(s["lat"], 2), round(s["lng"], 2)) == key:
                    s["embeds"].extend(c.get("embeds", []))
                    break
            continue
        seen_keys.add(key)
        spots.append({
            "id": ID_START + len(spots),
            "name": c["name"],
            "cat": c["cat"],
            "lat": c["lat"],
            "lng": c["lng"],
            "zip": c.get("zip", ""),
            "desc": c["desc"],
            "tags": c.get("tags", []),
            "danger": 2,                       # neutral default until reviewed
            "rating": None,
            "reviews": [],
            "embeds": c.get("embeds", []),
            "needs_review": True,
            "legal_status": c.get("legal_status", "unverified"),
            "source_author": c.get("author"),
        })
        passed += 1

    out_path = HERE / args.out
    js = ("// AUTO-GENERATED by promote.py from Reddit candidates. Do not hand-edit.\n"
          "// Every spot here is auto-collected and UNVERIFIED — review before trusting.\n"
          f"// Region: {C.REGION_NAME}. Count: {len(spots)}.\n"
          "window.INGESTED_SPOTS = " + json.dumps(spots, ensure_ascii=False, indent=1) + ";\n")
    out_path.write_text(js, encoding="utf-8")

    print(f"Read {total} candidates -> promoted {len(spots)} unique spots "
          f"(conf>={args.min_conf}, upvotes>={args.min_upvotes}).")
    print(f"Wrote {out_path}")
    print("To go live: add <script src=\"ingest/ingested-spots.js\"></script> and spread\n"
          "  ...(window.INGESTED_SPOTS || [])  into SEED_SPOTS in data.js. We do that together.")


if __name__ == "__main__":
    main()
